### ISSUE TITLE
Issues when running WebQuestions processing pipeline

### ISSUE THREAD

**Issue by luheng** [sivareddyg/UDepLambda#15]
Hi Siva,

I'm trying to run the pipeline specified in Makefile in order to generate deplambda data from raw questions. I encountered some error when running: make create_data_en:
zcat: can't stat: data/freebase/mid_to_key.txt.gz

Am I missing something here? 

Thanks!

**Comment by sivareddyg** [comment]
Hi Luheng,

Glad you are trying UDepLambda :). Appreciate it. Generating entity annotations and running the whole pipeline involves lot of resources like CoreNLP, Freebase API, Freebase endpoint and some additional files. Freebase API no longer works so some parts of the pipeline is broken. The code also supports KG API (the replacement of Freebase API) but it's accuracy is lower than Freebase API. The documentation for that is missing.

If you are interested in using UDepLambda without going through Freebase API, this is the best place to start https://github.com/sivareddyg/udeplambda#usage 

If you are interested in already entity annotated/linked data along with UDepLambda parses, try this https://github.com/sivareddyg/UDepLambda/blob/master/doc/FreebaseExperiments.md#multiligual-webquestions-and-graphquestions-data

But if you are interested in Freebase entity annotating and linking new data and then UDepLambda parsing, I can help in person since I am not sure what works and doesn't in your system. Even if I share data/freebase/mid_to_key.txt.gz, something else will be missing. Let's discuss over email/skype and set things up if this is important to you (PM me) . After that you can add the required documentation to the repo if you like.

Siva

**Comment by luheng** [comment]
Thanks Siva! I emailed you. Closing this issue now :)
